### ISSUE TITLE
Bitte Urheber angeben!

### ISSUE THREAD

**Issue by LostInDarkMath** [ScyllaHide/Exercises_SS19#1]
Es freut mich, dass du meinen Tex-Code wiederverwendest. Aber bitte gebe mich auch als Urheber an und verlinke auf mein Repo. Ansonsten ist das ein Copyright-Verstoß. 

Selbiges gilt übrigens auch für die Sachen, die im TUD_Math_BA-Repo liegen. Da würden auch einfach Dinge von mir kopiert, auch wenn leicht abgeändert.

**Comment by henrydatei** [comment]
Also in dem TUD_MATH_BA-Repo ist eine Verlinkung auf dein Repo. Die ist dort aber schon ne Weile.

**Comment by henrydatei** [comment]
Kannst du uns bitte sagen, welchen Code wir von dir benutzt haben sollen? Wenn es in den 2000 Zeilen Config-Zeug ist, dann müsste da mal epsilonbelowzero drübergucken, der hat das gemacht. Ich frag mal in meinem Repo rum, ob irgendwer Code von dir verwendet hat.

**Comment by LostInDarkMath** [comment]
Habe es im verknüpften Issue verlinkt.

**Comment by ScyllaHide** [comment]
Hab im September gar nicht nachgeschaut hier auf github und lese es jetzt erst. Also nochmal Sorry.

**Comment by ScyllaHide** [comment]
Ok ich habe jetzt ein vermerk auf den repo auf dem master hinzugefügt. Musst das mal auf den anderen branches auch hinzufügen und auch für das WS zeugs, was im Moment ehh noch Privat ist, aber was ich sicher nach dem Semester public stellen werde.

Nochmal Sorry.
